### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by Rajivhost** [ivelten/Graphscriber#1]
Hi Ismael,

Any plan to put this library on nuget?

**Comment by ivelten** [comment]
Yes, as soon as possible. Today I just finished testing all the code, so I'll be doing the FAKE build script next.

**Comment by ivelten** [comment]
@Rajivhost I am pretty close to finish it. I can't get it to build on Travis CI. For some reason, paket.exe is run two times when `dotnet build` is called, and then the build command crashes when restoring packages. Do you have any idea on what could be causing this problem?

https://travis-ci.org/ivelten/Graphscriber

**Comment by ivelten** [comment]
I was able to make it work. Apparently, `dotnet restore` calls Paket in parallel for each project, and Linux does not support paket running in parallel, so I had to do the restore and build sequentially, per project.

**Comment by Rajivhost** [comment]
Ok, great news, sorry for the late response.

**Comment by ivelten** [comment]
By the way, @Rajivhost, in this [pull request](https://github.com/ivelten/Graphscriber/pull/3) I just added support for connection initialization parameters, that can be used later for authorization, for example.

**Comment by Rajivhost** [comment]
Hi @ivelten, how about the release?

**Comment by ivelten** [comment]
Release its done.
